use crate::packet::mappings::{self, PacketId};

pub static SERVERBOUND_HANDSHAKE: &[&PacketId] = &[&mappings::serverbound::handshake::INTENTION];

pub static SERVERBOUND_STATUS: &[&PacketId] = &[
    &mappings::serverbound::status::PING_REQUEST,
    &mappings::serverbound::status::STATUS_REQUEST,
];

pub static SERVERBOUND_LOGIN: &[&PacketId] = &[
    &mappings::serverbound::login::COOKIE_RESPONSE,
    &mappings::serverbound::login::CUSTOM_QUERY_ANSWER,
    &mappings::serverbound::login::HELLO,
    &mappings::serverbound::login::KEY,
    &mappings::serverbound::login::LOGIN_ACKNOWLEDGED,
];

pub static SERVERBOUND_CONFIG: &[&PacketId] = &[
    &mappings::serverbound::config::ACCEPT_CODE_OF_CONDUCT,
    &mappings::serverbound::config::CLIENT_INFORMATION,
    &mappings::serverbound::config::COOKIE_RESPONSE,
    &mappings::serverbound::config::CUSTOM_CLICK_ACTION,
    &mappings::serverbound::config::CUSTOM_PAYLOAD,
    &mappings::serverbound::config::FINISH_CONFIGURATION,
    &mappings::serverbound::config::KEEP_ALIVE,
    &mappings::serverbound::config::PONG,
    &mappings::serverbound::config::RESOURCE_PACK,
    &mappings::serverbound::config::SELECT_KNOWN_PACKS,
];

pub static SERVERBOUND_PLAY: &[&PacketId] = &[
    &mappings::serverbound::play::ACCEPT_TELEPORTATION,
    &mappings::serverbound::play::ATTACK,
    &mappings::serverbound::play::BLOCK_ENTITY_TAG_QUERY,
    &mappings::serverbound::play::BUNDLE_ITEM_SELECTED,
    &mappings::serverbound::play::CHANGE_DIFFICULTY,
    &mappings::serverbound::play::CHANGE_GAME_MODE,
    &mappings::serverbound::play::CHAT,
    &mappings::serverbound::play::CHAT_ACK,
    &mappings::serverbound::play::CHAT_COMMAND,
    &mappings::serverbound::play::CHAT_COMMAND_SIGNED,
    &mappings::serverbound::play::CHAT_PREVIEW,
    &mappings::serverbound::play::CHAT_SESSION_UPDATE,
    &mappings::serverbound::play::CHUNK_BATCH_RECEIVED,
    &mappings::serverbound::play::CLIENT_COMMAND,
    &mappings::serverbound::play::CLIENT_INFORMATION,
    &mappings::serverbound::play::CLIENT_TICK_END,
    &mappings::serverbound::play::COMMAND_SUGGESTION,
    &mappings::serverbound::play::COMMAND_SUGGESTIONS,
    &mappings::serverbound::play::CONFIGURATION_ACKNOWLEDGED,
    &mappings::serverbound::play::CONTAINER_BUTTON_CLICK,
    &mappings::serverbound::play::CONTAINER_CLICK,
    &mappings::serverbound::play::CONTAINER_CLOSE,
    &mappings::serverbound::play::CONTAINER_SLOT_STATE_CHANGED,
    &mappings::serverbound::play::COOKIE_RESPONSE,
    &mappings::serverbound::play::CUSTOM_CLICK_ACTION,
    &mappings::serverbound::play::CUSTOM_PAYLOAD,
    &mappings::serverbound::play::DEBUG_SAMPLE_SUBSCRIPTION,
    &mappings::serverbound::play::DEBUG_SUBSCRIPTION_REQUEST,
    &mappings::serverbound::play::EDIT_BOOK,
    &mappings::serverbound::play::ENTITY_TAG_QUERY,
    &mappings::serverbound::play::INTERACT,
    &mappings::serverbound::play::JIGSAW_GENERATE,
    &mappings::serverbound::play::KEEP_ALIVE,
    &mappings::serverbound::play::LOCK_DIFFICULTY,
    &mappings::serverbound::play::MOVE_PLAYER_POS,
    &mappings::serverbound::play::MOVE_PLAYER_POS_ROT,
    &mappings::serverbound::play::MOVE_PLAYER_ROT,
    &mappings::serverbound::play::MOVE_PLAYER_STATUS_ONLY,
    &mappings::serverbound::play::MOVE_VEHICLE,
    &mappings::serverbound::play::PADDLE_BOAT,
    &mappings::serverbound::play::PICK_ITEM,
    &mappings::serverbound::play::PICK_ITEM_FROM_BLOCK,
    &mappings::serverbound::play::PICK_ITEM_FROM_ENTITY,
    &mappings::serverbound::play::PING_REQUEST,
    &mappings::serverbound::play::PLACE_RECIPE,
    &mappings::serverbound::play::PLAYER_ABILITIES,
    &mappings::serverbound::play::PLAYER_ACTION,
    &mappings::serverbound::play::PLAYER_COMMAND,
    &mappings::serverbound::play::PLAYER_INPUT,
    &mappings::serverbound::play::PLAYER_LOADED,
    &mappings::serverbound::play::PONG,
    &mappings::serverbound::play::PUNCH,
    &mappings::serverbound::play::RECIPE_BOOK_CHANGE_SETTINGS,
    &mappings::serverbound::play::RECIPE_BOOK_DATA,
    &mappings::serverbound::play::RECIPE_BOOK_SEEN_RECIPE,
    &mappings::serverbound::play::RENAME_ITEM,
    &mappings::serverbound::play::RESOURCE_PACK,
    &mappings::serverbound::play::SEEN_ADVANCEMENTS,
    &mappings::serverbound::play::SELECT_TRADE,
    &mappings::serverbound::play::SET_BEACON,
    &mappings::serverbound::play::SET_CARRIED_ITEM,
    &mappings::serverbound::play::SET_COMMAND_BLOCK,
    &mappings::serverbound::play::SET_COMMAND_MINECART,
    &mappings::serverbound::play::SET_CREATIVE_MODE_SLOT,
    &mappings::serverbound::play::SET_GAME_RULE,
    &mappings::serverbound::play::SET_JIGSAW_BLOCK,
    &mappings::serverbound::play::SET_STRUCTURE_BLOCK,
    &mappings::serverbound::play::SET_TEST_BLOCK,
    &mappings::serverbound::play::SIGN_UPDATE,
    &mappings::serverbound::play::SPECTATE_ENTITY,
    &mappings::serverbound::play::SPECTATOR_ACTION,
    &mappings::serverbound::play::STEER_VEHICLE,
    &mappings::serverbound::play::SWING,
    &mappings::serverbound::play::TELEPORT_TO_ENTITY,
    &mappings::serverbound::play::TEST_INSTANCE_BLOCK_ACTION,
    &mappings::serverbound::play::USE_ITEM,
    &mappings::serverbound::play::USE_ITEM_ON,
    &mappings::serverbound::play::WINDOW_CONFIRMATION,
];

pub static CLIENTBOUND_STATUS: &[&PacketId] = &[
    &mappings::clientbound::status::PONG_RESPONSE,
    &mappings::clientbound::status::STATUS_RESPONSE,
];

pub static CLIENTBOUND_LOGIN: &[&PacketId] = &[
    &mappings::clientbound::login::COOKIE_REQUEST,
    &mappings::clientbound::login::CUSTOM_QUERY,
    &mappings::clientbound::login::GAME_PROFILE,
    &mappings::clientbound::login::HELLO,
    &mappings::clientbound::login::LOGIN_COMPRESSION,
    &mappings::clientbound::login::LOGIN_DISCONNECT,
    &mappings::clientbound::login::LOGIN_FINISHED,
];

pub static CLIENTBOUND_CONFIG: &[&PacketId] = &[
    &mappings::clientbound::config::CLEAR_DIALOG,
    &mappings::clientbound::config::CODE_OF_CONDUCT,
    &mappings::clientbound::config::COOKIE_REQUEST,
    &mappings::clientbound::config::CUSTOM_PAYLOAD,
    &mappings::clientbound::config::CUSTOM_REPORT_DETAILS,
    &mappings::clientbound::config::DISCONNECT,
    &mappings::clientbound::config::FINISH_CONFIGURATION,
    &mappings::clientbound::config::KEEP_ALIVE,
    &mappings::clientbound::config::PING,
    &mappings::clientbound::config::POST_EFFECTS,
    &mappings::clientbound::config::REGISTRY_DATA,
    &mappings::clientbound::config::RESET_CHAT,
    &mappings::clientbound::config::RESOURCE_PACK_POP,
    &mappings::clientbound::config::RESOURCE_PACK_PUSH,
    &mappings::clientbound::config::SELECT_KNOWN_PACKS,
    &mappings::clientbound::config::SERVER_LINKS,
    &mappings::clientbound::config::SHOW_DIALOG,
    &mappings::clientbound::config::STORE_COOKIE,
    &mappings::clientbound::config::TRANSFER,
    &mappings::clientbound::config::UPDATE_ENABLED_FEATURES,
    &mappings::clientbound::config::UPDATE_TAGS,
];

pub static CLIENTBOUND_PLAY: &[&PacketId] = &[
    &mappings::clientbound::play::ACKNOWLEDGE_PLAYER_DIGGING,
    &mappings::clientbound::play::ADD_ENTITY,
    &mappings::clientbound::play::ADD_TRANSIENT_BLOCK,
    &mappings::clientbound::play::ANIMATE,
    &mappings::clientbound::play::AWARD_STATS,
    &mappings::clientbound::play::BLOCK_CHANGED_ACK,
    &mappings::clientbound::play::BLOCK_DESTRUCTION,
    &mappings::clientbound::play::BLOCK_ENTITY_DATA,
    &mappings::clientbound::play::BLOCK_EVENT,
    &mappings::clientbound::play::BLOCK_UPDATE,
    &mappings::clientbound::play::BOSS_EVENT,
    &mappings::clientbound::play::BUNDLE_DELIMITER,
    &mappings::clientbound::play::CHANGE_DIFFICULTY,
    &mappings::clientbound::play::CHAT,
    &mappings::clientbound::play::CHAT_PREVIEW_PACKET,
    &mappings::clientbound::play::CHUNKS_BIOMES,
    &mappings::clientbound::play::CHUNK_BATCH_FINISHED,
    &mappings::clientbound::play::CHUNK_BATCH_START,
    &mappings::clientbound::play::CLEAR_DIALOG,
    &mappings::clientbound::play::CLEAR_TITLES,
    &mappings::clientbound::play::COMBAT_EVENT,
    &mappings::clientbound::play::COMMANDS,
    &mappings::clientbound::play::COMMAND_SUGGESTIONS,
    &mappings::clientbound::play::CONTAINER_CLOSE,
    &mappings::clientbound::play::CONTAINER_SET_CONTENT,
    &mappings::clientbound::play::CONTAINER_SET_DATA,
    &mappings::clientbound::play::CONTAINER_SET_SLOT,
    &mappings::clientbound::play::COOKIE_REQUEST,
    &mappings::clientbound::play::COOLDOWN,
    &mappings::clientbound::play::CUSTOM_CHAT_COMPLETIONS,
    &mappings::clientbound::play::CUSTOM_PAYLOAD,
    &mappings::clientbound::play::CUSTOM_REPORT_DETAILS,
    &mappings::clientbound::play::DAMAGE_EVENT,
    &mappings::clientbound::play::DEBUG_BLOCK_VALUE,
    &mappings::clientbound::play::DEBUG_CHUNK_VALUE,
    &mappings::clientbound::play::DEBUG_ENTITY_VALUE,
    &mappings::clientbound::play::DEBUG_EVENT,
    &mappings::clientbound::play::DEBUG_SAMPLE,
    &mappings::clientbound::play::DELETE_CHAT,
    &mappings::clientbound::play::DISCONNECT,
    &mappings::clientbound::play::DISGUISED_CHAT,
    &mappings::clientbound::play::DISPLAY_CHAT_PREVIEW,
    &mappings::clientbound::play::ENTITY_EVENT,
    &mappings::clientbound::play::ENTITY_MOVEMENT,
    &mappings::clientbound::play::ENTITY_POSITION_SYNC,
    &mappings::clientbound::play::EXPLODE,
    &mappings::clientbound::play::FORGET_LEVEL_CHUNK,
    &mappings::clientbound::play::GAME_EVENT,
    &mappings::clientbound::play::GAME_RULE_VALUES,
    &mappings::clientbound::play::GAME_TEST_HIGHLIGHT_POS,
    &mappings::clientbound::play::HURT_ANIMATION,
    &mappings::clientbound::play::INITIALIZE_BORDER,
    &mappings::clientbound::play::KEEP_ALIVE,
    &mappings::clientbound::play::LEVEL_CHUNK_WITH_LIGHT,
    &mappings::clientbound::play::LEVEL_EVENT,
    &mappings::clientbound::play::LEVEL_PARTICLES,
    &mappings::clientbound::play::LIGHT_UPDATE,
    &mappings::clientbound::play::LOGIN,
    &mappings::clientbound::play::LOW_DISK_SPACE_WARNING,
    &mappings::clientbound::play::MAP_CHUNK_BULK,
    &mappings::clientbound::play::MAP_ITEM_DATA,
    &mappings::clientbound::play::MERCHANT_OFFERS,
    &mappings::clientbound::play::MOUNT_SCREEN_OPEN,
    &mappings::clientbound::play::MOVE_ENTITY_POS,
    &mappings::clientbound::play::MOVE_ENTITY_POS_ROT,
    &mappings::clientbound::play::MOVE_ENTITY_ROT,
    &mappings::clientbound::play::MOVE_MINECART_ALONG_TRACK,
    &mappings::clientbound::play::MOVE_PLAYER_ROT,
    &mappings::clientbound::play::MOVE_VEHICLE,
    &mappings::clientbound::play::NAMED_SOUND_EFFECT,
    &mappings::clientbound::play::OPEN_BOOK,
    &mappings::clientbound::play::OPEN_SCREEN,
    &mappings::clientbound::play::OPEN_SIGN_EDITOR,
    &mappings::clientbound::play::PING,
    &mappings::clientbound::play::PLACE_GHOST_RECIPE,
    &mappings::clientbound::play::PLAYER_ABILITIES,
    &mappings::clientbound::play::PLAYER_CHAT,
    &mappings::clientbound::play::PLAYER_CHAT_HEADER,
    &mappings::clientbound::play::PLAYER_COMBAT_END,
    &mappings::clientbound::play::PLAYER_COMBAT_ENTER,
    &mappings::clientbound::play::PLAYER_COMBAT_KILL,
    &mappings::clientbound::play::PLAYER_INFO,
    &mappings::clientbound::play::PLAYER_INFO_REMOVE,
    &mappings::clientbound::play::PLAYER_INFO_UPDATE,
    &mappings::clientbound::play::PLAYER_LOOK_AT,
    &mappings::clientbound::play::PLAYER_POSITION,
    &mappings::clientbound::play::PLAYER_ROTATION,
    &mappings::clientbound::play::PONG_RESPONSE,
    &mappings::clientbound::play::POST_EFFECTS,
    &mappings::clientbound::play::PROJECTILE_POWER,
    &mappings::clientbound::play::RECIPE_BOOK_ADD,
    &mappings::clientbound::play::RECIPE_BOOK_REMOVE,
    &mappings::clientbound::play::RECIPE_BOOK_SETTINGS,
    &mappings::clientbound::play::REMOVE_ENTITIES,
    &mappings::clientbound::play::REMOVE_MOB_EFFECT,
    &mappings::clientbound::play::RESET_SCORE,
    &mappings::clientbound::play::RESOURCE_PACK_POP,
    &mappings::clientbound::play::RESOURCE_PACK_PUSH,
    &mappings::clientbound::play::RESPAWN,
    &mappings::clientbound::play::ROTATE_HEAD,
    &mappings::clientbound::play::SCULK_VIBRATION_SIGNAL,
    &mappings::clientbound::play::SECTION_BLOCKS_UPDATE,
    &mappings::clientbound::play::SELECT_ADVANCEMENTS_TAB,
    &mappings::clientbound::play::SERVER_DATA,
    &mappings::clientbound::play::SERVER_LINKS,
    &mappings::clientbound::play::SET_ACTION_BAR_TEXT,
    &mappings::clientbound::play::SET_BORDER_CENTER,
    &mappings::clientbound::play::SET_BORDER_LERP_SIZE,
    &mappings::clientbound::play::SET_BORDER_SIZE,
    &mappings::clientbound::play::SET_BORDER_WARNING_DELAY,
    &mappings::clientbound::play::SET_BORDER_WARNING_DISTANCE,
    &mappings::clientbound::play::SET_CAMERA,
    &mappings::clientbound::play::SET_CARRIED_ITEM,
    &mappings::clientbound::play::SET_CHUNK_CACHE_CENTER,
    &mappings::clientbound::play::SET_CHUNK_CACHE_RADIUS,
    &mappings::clientbound::play::SET_COMPRESSION,
    &mappings::clientbound::play::SET_CURSOR_ITEM,
    &mappings::clientbound::play::SET_DEFAULT_SPAWN_POSITION,
    &mappings::clientbound::play::SET_DISPLAY_OBJECTIVE,
    &mappings::clientbound::play::SET_ENTITY_DATA,
    &mappings::clientbound::play::SET_ENTITY_LINK,
    &mappings::clientbound::play::SET_ENTITY_MOTION,
    &mappings::clientbound::play::SET_EQUIPMENT,
    &mappings::clientbound::play::SET_EXPERIENCE,
    &mappings::clientbound::play::SET_HEALTH,
    &mappings::clientbound::play::SET_HELD_SLOT,
    &mappings::clientbound::play::SET_OBJECTIVE,
    &mappings::clientbound::play::SET_PASSENGERS,
    &mappings::clientbound::play::SET_PLAYER_INVENTORY,
    &mappings::clientbound::play::SET_PLAYER_TEAM,
    &mappings::clientbound::play::SET_SCORE,
    &mappings::clientbound::play::SET_SIMULATION_DISTANCE,
    &mappings::clientbound::play::SET_SUBTITLE_TEXT,
    &mappings::clientbound::play::SET_TIME,
    &mappings::clientbound::play::SET_TITLES_ANIMATION,
    &mappings::clientbound::play::SET_TITLE_TEXT,
    &mappings::clientbound::play::SHOW_DIALOG,
    &mappings::clientbound::play::SIGN_UPDATE,
    &mappings::clientbound::play::SOUND,
    &mappings::clientbound::play::SOUND_ENTITY,
    &mappings::clientbound::play::SPAWN_EXPERIENCE_ORB,
    &mappings::clientbound::play::SPAWN_LIVING_ENTITY,
    &mappings::clientbound::play::SPAWN_PAINTING,
    &mappings::clientbound::play::SPAWN_PLAYER,
    &mappings::clientbound::play::SPAWN_WEATHER_ENTITY,
    &mappings::clientbound::play::START_CONFIGURATION,
    &mappings::clientbound::play::STOP_SOUND,
    &mappings::clientbound::play::STORE_COOKIE,
    &mappings::clientbound::play::SWING_ANIMATION,
    &mappings::clientbound::play::SYSTEM_CHAT,
    &mappings::clientbound::play::TAB_LIST,
    &mappings::clientbound::play::TAG_QUERY,
    &mappings::clientbound::play::TAKE_ITEM_ENTITY,
    &mappings::clientbound::play::TELEPORT_ENTITY,
    &mappings::clientbound::play::TEST_INSTANCE_BLOCK_STATUS,
    &mappings::clientbound::play::TICKING_STATE,
    &mappings::clientbound::play::TICKING_STEP,
    &mappings::clientbound::play::TITLE,
    &mappings::clientbound::play::TRANSFER,
    &mappings::clientbound::play::UNLOCK_RECIPES,
    &mappings::clientbound::play::UPDATE_ADVANCEMENTS,
    &mappings::clientbound::play::UPDATE_ATTRIBUTES,
    &mappings::clientbound::play::UPDATE_ENABLED_FEATURES,
    &mappings::clientbound::play::UPDATE_ENTITY_NBT,
    &mappings::clientbound::play::UPDATE_MOB_EFFECT,
    &mappings::clientbound::play::UPDATE_RECIPES,
    &mappings::clientbound::play::UPDATE_TAGS,
    &mappings::clientbound::play::USE_BED,
    &mappings::clientbound::play::WAYPOINT,
    &mappings::clientbound::play::WINDOW_CONFIRMATION,
    &mappings::clientbound::play::WORLD_BORDER,
];

use pumpkin_util::version::JavaMinecraftVersion;

fn clientbound_table(state: u8) -> Option<&'static [&'static PacketId]> {
    match state {
        1 => Some(CLIENTBOUND_STATUS),
        2 | 3 => Some(CLIENTBOUND_LOGIN),
        4 => Some(CLIENTBOUND_CONFIG),
        5 => Some(CLIENTBOUND_PLAY),
        _ => None,
    }
}

fn serverbound_table(state: u8) -> Option<&'static [&'static PacketId]> {
    match state {
        0 => Some(SERVERBOUND_HANDSHAKE),
        1 => Some(SERVERBOUND_STATUS),
        2 | 3 => Some(SERVERBOUND_LOGIN),
        4 => Some(SERVERBOUND_CONFIG),
        5 => Some(SERVERBOUND_PLAY),
        _ => None,
    }
}

/// A row with an id on the client wins; a row without one is still returned so
/// a step can retarget it, and the final lookup drops it if none does.
pub fn resolve_clientbound(
    state: u8,
    packet_id: i32,
    version: JavaMinecraftVersion,
) -> Option<&'static PacketId> {
    let mut retargetable = None;
    for &packet in clientbound_table(state)? {
        if packet.v26_3 != packet_id {
            continue;
        }
        if packet.to_id(version) != -1 {
            return Some(packet);
        }
        retargetable.get_or_insert(packet);
    }
    retargetable
}

pub fn resolve_serverbound(
    state: u8,
    packet_id: i32,
    version: JavaMinecraftVersion,
) -> Option<&'static PacketId> {
    let mut retargetable = None;
    for &packet in serverbound_table(state)? {
        if packet.to_id(version) != packet_id {
            continue;
        }
        if packet.v26_3 != -1 {
            return Some(packet);
        }
        retargetable.get_or_insert(packet);
    }
    retargetable
}
